name: Testing

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Golang code and linter code
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - uses: actions/setup-go@v2
      with:
        go-version: '1.22.2'

    - name: golangci-lint
      run: |
        go mod download
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1
        $(go env GOPATH)/bin/golangci-lint run --out-format=github-actions ./...

    - name: test
      run: |
        go test ./...